# Generated by Django 5.1.4 on 2024-12-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='currency_pair',
        ),
    ]
