name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpass
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Wait for MySQL
      run: sleep 20

    - name: Prepare database
      env:
        DB_NAME: testdb
        DB_USER: testuser
        DB_PASSWORD: testpass
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
      run: |
        source venv/bin/activate
        python manage.py migrate
        python manage.py populate_currencies
        python manage.py populate_all_data

    - name: Run tests
      env:
        DB_NAME: testdb
        DB_USER: testuser
        DB_PASSWORD: testpass
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
      run: |
        source venv/bin/activate
        python manage.py test
